#define RULESTRING "b3s23"
#define RULESTRING_SLASHED "B3/S23"
#define QUADROWS 4
#define BITTAGE 32
#define ROWS 32
#define THSPACE 28
#define MIDDLE28 0x3ffffffcu
typedef uint32_t urow_t;
#define STANDARD_LIFE 1
